Add SyncAPI support
kontent-ai/delivery-sdk-net pull request #372
Opened 2023-03-21 14:03 UTC by arguit

### Motivation

Implements issue #371 

### Checklist

- [ ] Code follows coding conventions held in this repo
- [ ] Automated tests have been added
- [ ] Tests are passing
- [ ] Docs have been updated (if applicable)
- [ ] Temporary settings (e.g. variables used during development and testing) have been reverted to defaults

### How to test

If manual testing is required, what are the steps?

2023-03-30 15:02 UTC, dzmitryk-kontent-ai requested changes

2023-03-30 15:05 UTC, arguit commented on Kontent.Ai.Delivery.Abstractions/Sync/IDeliverySyncResponse.cs
> +public interface IDeliverySyncResponse : IResponse
I have talked about this with Zdenek and the decision was to have both of them even though they are identical. They are different responses despite having the same attributes now.

2023-03-31 13:08 UTC, arguit commented on Kontent.Ai.Delivery/DeliveryClient.cs
> +        private async Task<ApiResponse> GetDeliveryResponseAsync(string endpointUrl, string continuationToken = null, HttpMethod httpMethod = null)
Refactored as suggested.

2023-04-06 12:47 UTC, dzmitryk-kontent-ai approved these changes

2023-04-06 12:55 UTC, merged